artifacts_root: artifacts

Data_Ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/sartajbhuvaji/brain-tumor-classification-mri/download?datasetVersionNumber=2
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

Data_Validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_dir: artifacts/data_ingestion

Data_Transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  train_path: artifacts/data_transformation/train
  test_path: artifacts/data_transformation/test

Model_Trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_ingestion/train
  test_path: artifacts/data_ingestion/test/
  preprocessor_path: artifacts/data_transformation/model.h5

Model_Evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test/
  model_path: artifacts/model_trainer/model.h5
  metric_file: artifacts/model_evaluation/metrics.json
