ResNet50:
  input_tensor: Input(input_shape=224,224,3)
  weights: imagenet
  include_top: False
  optimizer: rmsprop #adam
  pooling: avg #max, None
  loss: categorical_crossentropy
  epochs: 5
  metrics: accuracy

VGG16:
  input_tensor: Input(input_shape=224,224,3)
  weights: imagenet
  include_top: False
  optimizer: rmsprop #adam
  pooling: avg #max, None
  loss: categorical_crossentropy
  metrics: accuracy
  epochs: 1
