artifacts_root: artifacts

Data_Ingestion:
  root_dir: artifacts/data_ingestion
  source_path: dataset
  local_data_path: artifacts/data_ingestion/

Data_Validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_dir: artifacts/data_ingestion

Data_Transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  local_data_path: artifacts/data_transformation/datasets.pkl

Model_Trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_ingestion/Training
  test_path: artifacts/data_ingestion/Testing/
  model_path: artifacts/model_trainer/

Model_Evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/Testing/
  model_path: artifacts/model_trainer/
  best_model_path: artifacts/model_evaluation/
  metric_file: artifacts/model_evaluation/
